<?php
// $Id: casetracker_basic.module,v 1.22 2009/02/09 23:22:58 jmiccolis Exp $

/**
 * @file
 * Enables a basic project node type for use with Case Tracker.
 */

/**
 * Implementation of hook_perm().
 */
function casetracker_basic_perm() {
  return array('create projects', 'create cases', 'edit own projects', 'edit own cases');
}

/**
 * Implementation of hook_node_info().
 */
function casetracker_basic_node_info() {
  return array(
    'casetracker_basic_project' => array(
      'name'        => t('Project'),
      'module'      => 'node',
      'description' => t('Create a basic project for use with Case Tracker.'),
      'help'        => t('Create a basic project for use with Case Tracker.'),
      'body_label'  => t('Description'),
    ),
    'casetracker_basic_case' => array(
      'name'        => t('Case'),
      'module'      => 'node',
      'description' => t('Open a new case assigned to a particular project.'),
      'help'        => t('Open a new case assigned to a particular project.'),
      'body_label'  => t('Description'),
    ),
  );
}

/**
 * Implementation of hook_default_casetracker_templates()
 */
function casetracker_basic_default_casetracker_templates() {
  $templates = array();
  $template = new stdClass();
  $template->name = 'basic';
  $template->properties = array();
  
  $property = new stdClass();
  $property->type = 'casetracker_property_state';
  $property->realm = 'status';
  $property->name = t('Status');
  // $property->options = array('open', 'closed');
  $property->default = 'open';
  $template->properties[] = $property;
  
  $property = new stdClass();
  $property->type = 'casetracker_property_user';
  $property->view = '';
  $property->name = t('Assigned');
  // $property->options = array('open', 'closed');
  // $property->default = 'open';
  $template->properties[] = $property;

  
  $templates['basic'] = $template;
  return $templates;
}

/**
 * Implementation of hook_default_casetracker_states()
 */
function casetracker_basic_default_casetracker_states() {
  $properties = array();
  $property = new stdClass();
  $property->name = 'closed';
  $property->title = t('Closed');
  $property->realm = 'status';
  $property->weight = 1;
  $properties[] = $property;
  
  $property = new stdClass();
  $property->name = 'open';
  $property->title = t('Open');
  $property->realm = 'status';
  $property->weight = 0;
  $properties[] = $property;
  
  return $properties;
}
